### ISSUE TITLE
> # Venho aqui para pedir ajuda em um projeto

### ISSUE THREAD

**Issue by LuanPetruitis** [LuanPetruitis/financeiro#1]
> # Venho aqui para pedir ajuda em um projeto
> ### Gostaria que alguma pessoa que tivesse conhecimento em JAVASCRIPT me ajuda-se neste projeto.
> [Controle de despesas](https://github.com/LuanPetruitis/financeiro)
> 
> Eu estou usando função para mudar o valor da receita ou da despesa mas quando aperto o botão ele muda o valor rapidamente e depois volta ao normal.

Olá @LuanPetruitis, está fazendo este Controle de Despesas baseado em algum curso on-line ou apostila? Compartilha aê. Eu ainda não domino JS, achei interessante, deu a entender que a "variável" não está armazenando o valor, "zerando" quando a página atualiza, também fiquei curioso na resolução deste problema.

_Originally posted by @adrianomatos in https://github.com/gustavoguanabara/git-github/issues/3#issuecomment-628211016_

**Comment by LuanPetruitis** [comment]
Então na realidade não é de nenhum curso eu peguei neste repositório [controle-de-despesas,](https://github.com/Roger-Melo/controle-de-despesas) ai estou tentando mudar o valor mas ele muda na hora que eu clico em adicionar e em menos de um segundo volta para zero;

Muito obrigado pela sua colaboração!

![editada](https://user-images.githubusercontent.com/62400514/80145981-764c1c00-8587-11ea-81a0-e096b7749ce9.jpg)

Conheça meus projetos:

- Para quem quiser me seguir meu [Instagram](https://www.instagram.com/lupetrutio/)

- Meus repositórios no [GitHub](https://github.com/LuanPetruitis?tab=repositories)

- Meu  [Facebook](https://www.facebook.com/luan.petruitis/)

**Comment by adrianomatos** [comment]
Já assistiu a vídeo-aula dele? 

[Como desenvolver um controle financeiro com JavaScript puro](https://www.youtube.com/watch?v=xarRciYWT5Q&feature=youtu.be)

**Comment by LuanPetruitis** [comment]
Não ainda não vou assistir nala mostra fazer este procedimento

**Comment by LuanPetruitis** [comment]
Eu vou assistir a vídeo aula **MUITO OBRIGADO!**
